# Generated by Django 5.1.1 on 2024-09-22 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_coupon_remove_payment_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='imp_uid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='merchant_uid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(default='ready', max_length=20),
        ),
    ]
