# Generated by Django 5.1.1 on 2024-09-22 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_imp_uid_payment_merchant_uid_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='imp_uid',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='merchant_uid',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
    ]
