# Generated by Django 5.1.1 on 2024-09-23 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_course'),
        ('payments', '0004_remove_payment_imp_uid_remove_payment_merchant_uid_and_more'),
    ]

    operations = [
    ]
