# Generated by Django 5.1.1 on 2024-09-22 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_certificate_verification_code_and_more'),
    ]

    operations = [
    ]
