# Generated by Django 5.1.1 on 2024-09-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lesson_prerequisite_courseprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseprogress',
            name='last_completed_lesson',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='prerequisite',
        ),
        migrations.AddField(
            model_name='courseprogress',
            name='completed_lessons',
            field=models.ManyToManyField(blank=True, to='courses.lesson'),
        ),
    ]
