# Generated by Django 5.1.1 on 2024-09-14 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('github', 'GitHub'), ('html_css', 'HTML/CSS'), ('js', 'JavaScript'), ('express', 'Express'), ('mongodb', 'MongoDB'), ('aws', 'AWS'), ('project', 'Project')], max_length=20)),
                ('question', models.TextField()),
                ('type', models.CharField(choices=[('multiple_choice', '5지선다형'), ('code_submission', '코드 제출형')], max_length=20)),
                ('exam_type', models.CharField(choices=[('midterm', '중간고사'), ('final', '기말고사')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MissionSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='missions.mission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoiceMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.JSONField()),
                ('correct_answer', models.CharField(max_length=1)),
                ('mission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='multiple_choice', to='missions.mission')),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoiceSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(max_length=1)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='multiple_choice', to='missions.missionsubmission')),
            ],
        ),
    ]
