# Generated by Django 5.1.1 on 2024-09-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='course',
            field=models.CharField(choices=[('math', '수학'), ('science', '과학'), ('history', '역사'), ('literature', '문학')], max_length=20),
        ),
    ]
