# Generated by Django 5.1.1 on 2024-09-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoicemission',
            name='options',
            field=models.TextField(),
        ),
    ]
