# Generated by Django 5.1.1 on 2024-09-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_alter_mission_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionsubmission',
            name='selected_options',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
