# Generated by Django 5.1.1 on 2024-09-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0003_missionsubmission_selected_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='correct_answer',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
