# Generated by Django 5.1.1 on 2024-09-13 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0004_alter_mission_correct_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missionsubmission',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='missionsubmission',
            name='submission',
        ),
        migrations.RemoveField(
            model_name='missionsubmission',
            name='submitted_at',
        ),
    ]
