# Generated by Django 5.1.1 on 2024-09-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0005_remove_missionsubmission_is_correct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
